# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 07cd4ab010929746a22604919a850bebdcaba8a54da3f9ff0627e6c03c6e049ce8f62623c898f3e785ec887975bcebbd186d96536a6d91491f416b0af3b2dbe8

test:
  secret_key_base: 3a9d6714d7f0427965599d5bf0d8cbf6a990f7289c7c32705e6146dce07d9dc885f3d52cd7a94820353c081b90cf714df191ba93bee941a73c6e64b6dd7567cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
